import type { Metadata } from "next";
import "@/styles/global.css";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import Footer from '@/components/footer.tsx'
import Header from '@/components/header.tsx'
import { Geist, Geist_Mono } from 'next/font/google'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})



const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <div className="px-1 text-gray-700 antialiased m-12 mt-6">
          <div className="mx-auto max-w-screen-lg ">
            <ClerkProvider>
              <div className="flex flex-col justify-between h-screen">
                <Header />
                <main className="flex-1">{children}</main>
                <Footer />
              </div>
            </ClerkProvider>
            </div>
          </div>
      </body>
    </html>
  );
}
