import "./globals.css"
import type { Metadata } from "next";
import BasicLayout from '@/layouts/basic'
import ThemeProvider from "@/components/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <BasicLayout>{children}</BasicLayout>
          </ThemeProvider>
      </body>
    </html>
  );
}
