import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Link from '@repo/ui/link'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton />
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           <ThemeProvider>
//             <Header />
//             {children}
//             <Footer />
//           </ThemeProvider>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {

  return (
    <html lang="en">
      <head></head>
      <body>
        {children}
      </body>
    </html>
  );
}